//Constants for redux actions

export const CHANGE_SEARCH_BOX = 'CHANGE_SEARCH_BOX';
export const POKEMON_FETCH_PENDING = 'POKEMON_FETCH_PENDING';
export const POKEMON_FETCH_SUCCESS = 'POKEMON_FETCH_SUCCESS';
export const POKEMON_FETCH_FAILED = 'POKEMON_FETCH_FAILED';